### PR TITLE
Added option for spell damage

### PR DESCRIPTION
**Pull request by valcorin**
Added the ability to send spell impact and spell aspect as part of game.hm3.macros.injuryRoll

### CODE REVIEW

**Comment by valcorin** [comment]
Here is an example macro from the macro section for the spell. Basically, you add
rollResult.spell_aspect = "Fire";
rollResult.spell_impact = rndInt;

to get the prompt since impact is undefined or you can add
rollResult.aspect = "Fire";
rollResult.impact = rndInt;

to bypass the dialog since impact is defined (as already coded).

My fork of the [Requestor](https://github.com/valcorin/requestor) module submits the macro and necessary data so that the GM can click it.  This is how I'm getting around the permission issue I run into if I try to have the player apply it directly to the creature.

```
let rollRes = "CS"
let fatigue = "0"
switch (rollResult.result) {
  case 'MS':
    rollRes = "MS"
    fatigue = "-1";
    break;
  case 'MF':
    rollRes = "MF"
    fatigue = "-1";
    break;
  case 'CF':
    rollRes = "CF"
    fatigue = "-2";
    break;
}
const targets = game.user.targets;
if (!targets?.size) {
  const spellName = item.name;
  let curr_fatigue = token.document._actor.system.fatigue
  console.log("Current fatigue: " + curr_fatigue)
  ui.notifications.warn(`No targets selected. You must select one or more targets; spell ${spellName} aborted.  Correct fatigue by ${fatigue}`);
  return;
}
const target_arr = Array.from(targets)

let result = ''

if (rollRes == 'CS' || rollRes == 'MS') {
  for (let i = 0; i < target_arr.length; i++) {
    const targetToken = target_arr[i];
    if (typeof targetToken == "undefined") {
      console.log("No more targets.")
      break;
    }
    const target_actor = targetToken.document._actor
    const rndInt = Math.floor(Math.random() * 6) + 1
    rollResult.spell_aspect = "Fire";
    rollResult.spell_impact = rndInt;
    rollResult.aim = "Mid";
    await Requestor.request({
      description: result,
      sound: "worlds/novendo/sounds/heatwave.ogg",
      img: target_actor.thumbnail,
      buttonData: [{
        actor_from_token_ID: targetToken.id,
        amount: rollResult,
        permission: "GM",
        limit: 1,
        label: "Determine injury to " + target_actor.name,
        action: async () => {
	    await game.hm3.macros.injuryRoll(actor, amount);
        }
      }]
    });
  }
}
```

**Comment by valcorin** [comment]
Reapplied changes to 1.4.5 and verified they are working as expected

**Comment by toastygm** [comment]
Overall, I'm not excited about the idea of creating a special case for Spell impact.  What it seems is that you are trying to be able to handle "Fire" impact type.  But maybe I'm wrong.  What is it you are trying to accomplish?

**Comment by toastygm** [comment]
After a little more reading, it seems what you are really trying to accomplish are:
1) The ability to set a fixed aspect that the user cannot change.
2) The ability to specify the default to use for impact (instead of defaulting to 0 in the dialog)
3) The ability to bypass the dialog box altogether and simply use the provided aspect and impact.

Is this correct?

In that case, I would rather implement those capabilities so they are usable beyond simply spells; those should be usable by weapons or any Injury Roll.

**Comment by valcorin** [comment]
All I'm doing is allowing spell casting to tie into the back-half of the automated process.  Since it is all weapon based, I am sending down the needed numbers so I can plug them in and call the Injury stuff normally.

Players cannot affect monster tokens (gives permission error), so I have to generate a Request for the GM to click to apply the results.

Obviously, I'm new to this so if there is a way to do it better please let me know.  So far, I haven't been able to get Spells to tie in any other way.

Combat for Spells:
1) Player targets creatures
2) Casts spell macro
3) Macro generates a Request to the GM with the appropriate type and damage (as far as I can see only Fire exists for non-physical aspects).
4) GM clicks button and the damage is applied to the creature.

image

**Comment by valcorin** [comment]
By adding tokenID, it now targets and calculates the creature attacked with a spell.

 // Prepare for Chat Message
        const chatTemplate = 'systems/hm3/templates/chat/injury-card.html';

        const chatTemplateData = mergeObject({
            title: `${rollData.actor.token ? rollData.actor.token.name : rollData.actor.name} Injury`,
            visibleActorId: rollData.actor.id,
            tokenId: rollData.actor.token.id
        }, result);


image

**Comment by valcorin** [comment]
The upshot is that spells are now much more automated in a fashion similar to normal combat with the one exception of the creature not being able to dodge/block/ignore (I calculate that on a per spell basis as best I can).

**Comment by toastygm** [comment]
Why don't you please DM me on discord so we can discuss.  Now that I understand what you are doing, I have some recommendations on a different approach that is more in line with what is done during automated combat.

**Pull request closed without merging**
