### PR TITLE
Option for multiplier

### PR DESCRIPTION
**Pull request by valcorin**
Simple change to allow passing in a multiplier so it can be something other than 5

### CODE REVIEW

**Comment by toastygm** [comment]
What is the use case here?  Why would you ever multiply by anything other than 5?

When converting a 3d6 roll to a d100 roll, you multiply by 5 to get a value from 15-90.  If you use any other multiplier, this math does not work out.  Under what conditions would you ever use any other multiplier?

I've never seen in the rules any reason for a different multiplier.

**Comment by valcorin** [comment]
It's for the target.  Maybe I seriously misunderstood the code, but there are cases where the target is say Will x 3 instead of x 5.
I thought that was setting the target, not converting an Xd6 roll.

**Comment by valcorin** [comment]
Here's an example of why I thought it was working:
Spell:  Once invoked the sphere will start to glow hypnotically, potentially mesmerizing those within SI meters (to a maximum of 7 meters). Those in line of sight roll 1d100 vs a multiple of Will (MS: Will x 3; CS: Will x 2) or be ensnared. Any attack on a victim will break the spell on that victim.
BallsofWonderTest
DevrikStats

**Comment by valcorin** [comment]
And here's a critical showing the correct 22 target.
BallsofWonderTestCrit

**Comment by toastygm** [comment]
Got it.  Ok, sounds good.

**Review by toastygm — APPROVED** [review]
Approved.

**Pull request merged**
